
version: '3.3'
services:
  test:
    build: .
    container_name: testing
    volumes:
      - .:/app
    # command: [ "pytest-watch", "--ext=.py,.yaml", "--","-s","--tb=line" ]
  component-test:
    build: 
      context: .
      dockerfile: Dockerfile.component 
    container_name: component-test
    command: [ "ptw","--","-sv" ]

    volumes:
      - ./custom_components/entrance_controller/__init__.py:/usr/src/app/homeassistant/components/entrance_controller/__init__.py:ro
      - ./tests/test_lightingsm.py:/usr/src/app/tests/components/test_lightingsm.py:ro
      - ./pytest.ini:/usr/src/app/pytest.ini:ro
  component-test-ci:
    build: 
      context: .
      dockerfile: Dockerfile.component 
    container_name: component-test-ci
    command: [ "pytest" ]

    volumes:
        # - G:\Repos\hass-dev:/config
      - ./custom_components/entrance_controller/__init__.py:/usr/src/app/homeassistant/components/entrance_controller/__init__.py:ro
      - ./tests/test_lightingsm.py:/usr/src/app/tests/components/test_lightingsm.py:ro
      - ./pytest.ini:/usr/src/app/pytest.ini:ro
        # - ${PWD}:/usr/src/app

